- hosts: SQL0, SQL1, SQL2
  roles: 
    - role: mariadb

- hosts: SQL0
  roles:
    - role: sql0

- hosts: SQL1
  roles:
    - role: sql1

- hosts: SQL2
  roles:
    - role: sql2

- hosts: LB
  roles:
    - role: haproxy
